# Generated by Django 3.2.3 on 2021-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_number_user_meli_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('student', 'student'), ('mentor_parvareshi', 'mentor_parvareshi'), ('amoozeshi_mentor', 'amoozeshi_mentor'), ('pazhooheshi_mentor', 'pazhooheshi_mentor'), ('pazhooheshi_mentor', 'pazhooheshi_mentor'), ('varzeshi_mentor', 'varzeshi_mentor'), ('manager', 'manager')], default=5, max_length=20),
            preserve_default=False,
        ),
    ]
