# Generated by Django 3.2.3 on 2021-06-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AlterField(
            model_name='user',
            name='meli_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
