# Generated by Django 3.2.3 on 2021-06-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210607_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('student', 'student'), ('mentor', 'mentor'), ('manager', 'manager')], default='student', max_length=20),
            preserve_default=False,
        ),
    ]
