# Generated by Django 3.2.3 on 2021-06-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('photo', models.ImageField(upload_to='photoes/students/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('field', models.CharField(choices=[('پرورشی', 'پرورشی'), ('آموزشی', 'آموزشی'), ('پژوهشی', 'پژوهشی'), ('ورزشی', 'ورزشی')], max_length=50)),
                ('level', models.CharField(choices=[('مدرسه', 'مدرسه'), ('ناحیه', 'ناحیه'), ('شهر', 'شهر'), ('استان', 'استان'), ('کشور', 'کشور'), ('بین الملل', 'بین الملل')], max_length=50)),
                ('dore', models.CharField(choices=[('اول', 'اول'), ('دوم', 'دوم')], max_length=50)),
                ('pic', models.ImageField(blank=True, upload_to='photoes/achievement/%Y/%m/%d')),
                ('video_link', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True, max_length=1024)),
                ('refrence_id', models.IntegerField(null=True)),
                ('modify_level', models.CharField(blank=True, choices=[('student', 'student'), ('mentor', 'mentor'), ('manager', 'manager')], max_length=50)),
                ('is_main', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.student')),
            ],
            options={
                'permissions': (('parvareshi_mentor', 'can view parvareshi'), ('amoozeshi_mentor', 'can view amoozeshi'), ('pazhooheshi_mentor', 'can view pazhooheshi'), ('varzeshi_mentor', 'can view varzeshi')),
            },
        ),
    ]
