# Generated by Django 3.2.3 on 2021-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_achievement_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='year',
            field=models.IntegerField(choices=[(1385, 1385), (1386, 1386), (1387, 1387), (1388, 1388), (1389, 1389), (1390, 1390), (1391, 1391), (1392, 1392), (1393, 1393), (1394, 1394), (1395, 1395), (1396, 1396), (1397, 1397), (1398, 1398), (1399, 1399), (1400, 1400), (1401, 1401)]),
        ),
    ]
