# Generated by Django 3.2.3 on 2021-06-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_achievement_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='meli_code',
            field=models.CharField(default=1111111111, max_length=10),
            preserve_default=False,
        ),
    ]
