# Generated by Django 3.2.3 on 2021-06-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_student_meli_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='meli_code',
        ),
    ]
