# Generated by Django 3.2.3 on 2021-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_remove_student_meli_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='meli_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
