# Generated by Django 3.2.3 on 2021-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_student_meli_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(help_text='بیبلب', max_length=50),
        ),
    ]
