# Generated by Django 3.2.4 on 2021-06-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_achievement_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='field',
            field=models.CharField(choices=[('پرورشی', 'پرورشی'), ('آموزشی', 'آموزشی'), ('پژوهشی', 'پژوهشی'), ('ورزشی', 'ورزشی')], max_length=50),
        ),
    ]
